### PR TITLE
Improve shell compatibility

### PR DESCRIPTION
**Pull request by afiram**
add newline to patch command pipeline. 

please review.

----------------
detail.

patching with cookiepatcher claim `malformed patch` sometimes.
```
cookiepatcher
patching file xxx.py
patch unexpectedly ends in middle of line
patch: **** malformed patch at line 54:
```

but, execute direct cli shell patch(1) commad is success with same context diff.

```
cat xxx.patch | patch -p1 
patching file xxx.py
Hunk #1 succeeded at 20 with fuzz 2 (offset 12 lines).
```

I think `shell redirect` adding newline, maybe.

### CODE REVIEW

**Comment by hirokiky** [comment]
@afiram Thank you for your PR.

Can you show me diff between your `xxx.patch` and the `rendered` object in the `cookiepatch` function?
I have not got this situation yet, so I just want to know.

**Comment by hirokiky** [comment]
@afiram also, please fix the number of spaces before `rendered += ...` line.

**Comment by hirokiky** [comment]
I added @afiram as a collaborator of this repo.

**Comment by afiram** [comment]
@hirokiky 

> Can you show me diff between your xxx.patch and the rendered object in the cookiepatch function?

unfortunately, xxx.patch can not show to public, so we send xxx.patch to private channel.
but, xxx.patch is rendered string. it same. (xxx.patch is `cookiepatcher --show` outputs)

**Comment by hirokiky** [comment]
@afiram Thank you so much! I'll merge it.

**Pull request merged**
