### PR TITLE
Fix cookiecutter 1.5 expand abbreviations

### PR DESCRIPTION
**Pull request by afiram**
fix import error when cookiecutter 1.5.

```
  File "xxx/.virtualenvs/python-3.5.1/lib/python3.5/site-packages/cookiepatcher/main.py", line 8, in <module>
    from cookiecutter.main import expand_abbreviations
ImportError: cannot import name 'expand_abbreviations'
```

here is cookiecutter changed commit.

https://github.com/audreyr/cookiecutter/commit/12de75bb23e3f05fb1807b1b5d357cf9cfc0accd

@hirokiky please review.

### CODE REVIEW

**Comment by hirokiky** [comment]
Thanks for your report and submitting the patch.

hmm how about drop supporting old cookie cutters? (specifying versions by setup.py is needed.

**Comment by hirokiky** [comment]
I think using distutils is too much.
Just importing from cookiecutter.main

```
+ from cookiecutter.main import expand_abbreviations
```

and specifying the version >= 1.5 is better.

**Comment by hirokiky** [comment]
Or. you need to use old version of cookiecutter?

**Comment by afiram** [comment]
ok.  I agree that.  please check commit 08f5cce.
thanks your reply.

**Comment by hirokiky** [comment]
awesome!

**Pull request merged**
